# Generated by Django 5.2 on 2025-04-23 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('time', models.TimeField(verbose_name='Time')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('is_pleasant', models.BooleanField(verbose_name='Is pleasant')),
                ('periodicity', models.CharField(choices=[('1_day', 'Every 1 day'), ('3_days', 'Every 3 days'), ('7_days', 'Every 7 days')], default='1_day', max_length=30, verbose_name='Periodicity')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reward')),
                ('lead_time', models.DurationField(verbose_name='Lead time')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='habits.habits', verbose_name='Related habit')),
            ],
        ),
    ]
