# Generated by Django 5.2 on 2025-04-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
