# Generated by Django 5.2 on 2025-04-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habits_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='is_pleasant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='habits',
            name='lead_time',
            field=models.CharField(default='10 minutes', max_length=255),
        ),
    ]
