# Generated by Django 5.2 on 2025-04-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habits_is_pleasant_alter_habits_lead_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='periodicity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Every 1 day'), (3, 'Every 3 days'), (7, 'Every 7 days')], default=1, verbose_name='Periodicity'),
        ),
    ]
